package com.flatcode.littlemusicadmin.Unit;

import com.flatcode.littlemusicadmin.Activity.AlbumAddActivity;
import com.flatcode.littlemusicadmin.Activity.AlbumEditActivity;
import com.flatcode.littlemusicadmin.Activity.AlbumSongsActivity;
import com.flatcode.littlemusicadmin.Activity.AlbumsActivity;
import com.flatcode.littlemusicadmin.Activity.ArtistAddActivity;
import com.flatcode.littlemusicadmin.Activity.ArtistEditActivity;
import com.flatcode.littlemusicadmin.Activity.ArtistSongsActivity;
import com.flatcode.littlemusicadmin.Activity.ArtistsActivity;
import com.flatcode.littlemusicadmin.Activity.CategoriesActivity;
import com.flatcode.littlemusicadmin.Activity.CategoryAddActivity;
import com.flatcode.littlemusicadmin.Activity.CategoryEditActivity;
import com.flatcode.littlemusicadmin.Activity.CategorySongsActivity;
import com.flatcode.littlemusicadmin.Activity.EditorsChoiceActivity;
import com.flatcode.littlemusicadmin.Activity.EditorsChoiceAddActivity;
import com.flatcode.littlemusicadmin.Activity.FavoritesActivity;
import com.flatcode.littlemusicadmin.Activity.MainActivity;
import com.flatcode.littlemusicadmin.Activity.PrivacyPolicyActivity;
import com.flatcode.littlemusicadmin.Activity.PrivacyPolicyEditActivity;
import com.flatcode.littlemusicadmin.Activity.ProfileActivity;
import com.flatcode.littlemusicadmin.Activity.ProfileEditActivity;
import com.flatcode.littlemusicadmin.Activity.SliderShowActivity;
import com.flatcode.littlemusicadmin.Activity.SongAddActivity;
import com.flatcode.littlemusicadmin.Activity.SongEditActivity;
import com.flatcode.littlemusicadmin.Activity.SongsActivity;
import com.flatcode.littlemusicadmin.Activity.SplashActivity;
import com.flatcode.littlemusicadmin.Activity.UsersActivity;
import com.flatcode.littlemusicadmin.Auth.ForgetPasswordActivity;
import com.flatcode.littlemusicadmin.Auth.LoginActivity;

public class CLASS {
    public static Class MAIN = MainActivity.class;
    public static Class SPLASH = SplashActivity.class;
    public static Class LOGIN = LoginActivity.class;
    public static Class FORGET_PASSWORD = ForgetPasswordActivity.class;
    public static Class PROFILE = ProfileActivity.class;
    public static Class PROFILE_EDIT = ProfileEditActivity.class;
    public static Class SLIDER_SHOW = SliderShowActivity.class;
    public static Class SONG_ADD = SongAddActivity.class;
    public static Class SONG_EDIT = SongEditActivity.class;
    public static Class SONGS = SongsActivity.class;
    public static Class USERS = UsersActivity.class;
    public static Class CATEGORY_ADD = CategoryAddActivity.class;
    public static Class CATEGORY_EDIT = CategoryEditActivity.class;
    public static Class CATEGORY_SONGS = CategorySongsActivity.class;
    public static Class CATEGORIES = CategoriesActivity.class;
    public static Class ALBUM_ADD = AlbumAddActivity.class;
    public static Class ALBUM_EDIT = AlbumEditActivity.class;
    public static Class ALBUMS = AlbumsActivity.class;
    public static Class ALBUM_SONGS = AlbumSongsActivity.class;
    public static Class ARTIST_ADD = ArtistAddActivity.class;
    public static Class ARTIST_EDIT = ArtistEditActivity.class;
    public static Class ARTISTS = ArtistsActivity.class;
    public static Class ARTIST_SONGS = ArtistSongsActivity.class;
    public static Class FAVORITES = FavoritesActivity.class;
    public static Class PRIVACY_POLICY = PrivacyPolicyActivity.class;
    public static Class PRIVACY_POLICY_EDIT = PrivacyPolicyEditActivity.class;
    public static Class EDITORS_CHOICE = EditorsChoiceActivity.class;
    public static Class EDITORS_CHOICE_ADD = EditorsChoiceAddActivity.class;
}